name: update readme schedule

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run
        working-directory: scripts
        run: |
          python update.py
          mv README.md ./../README.md
      - name: commit
        id: commit
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git diff-index --quiet HEAD || (git commit -m 'update README.md' && echo "::set-output name=push::true")
      - name: push
        if: steps.commit.outputs.push
        run: git push origin HEAD:main
